disabled_rules:
    - identifier_name
    - statement_position
    - todo

line_length: 300

trailing_whitespace:
  ignores_empty_lines: true
  severity: warning

nesting:
  type_level: 2

excluded:
  - .build
  - vendor
